name: vocab_booster
description: "An application for boosting vocabulary of the learner."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  signals: ^5.2.2
  go_router: ^14.2.0
  flex_color_scheme: ^7.3.1
  shared_preferences: ^2.2.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
