name: vocab_booster
description: "An application for boosting vocabulary of the learner."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.11
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  auto_route: ^8.2.0
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  shadcn_ui: ^0.5.7
  flutter_localization: ^0.2.0
  intl_utils: ^2.8.7
  intl: ^0.19.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_lucide: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0

flutter_intl:
  enabled: true
  class_name: L10N
  main_locale: en
  arb_dir: lib/packages/core/l10n
  output_dir: lib/packages/core/l10n/generated

targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
      generate_for:
        - lib/ui/**/**.dart

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/misc/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
