name: vocab_booster
description: "An application for boosting vocabulary of the learner."

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.11
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  auto_route: ^8.2.0
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  shadcn_ui: ^0.6.2
  flutter_localization: ^0.2.0
  intl_utils: ^2.8.7
  intl: ^0.19.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_lucide: ^1.3.0
  syncfusion_flutter_charts: ^26.1.40
  sentry_flutter: ^8.3.0
  card_swiper: ^3.0.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  expandable_page_view: ^1.0.17
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1
  talker: ^4.3.2
  talker_dio_logger: ^4.3.2
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.0.0
  flutter_timezone: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0

flutter_intl:
  enabled: true
  class_name: L10N
  main_locale: en
  arb_dir: lib/packages/core/l10n
  output_dir: lib/packages/core/l10n/generated

targets:
  $default:
    builders:
      auto_route_generator:auto_route_generator:
      generate_for:
        - lib/ui/**/**.dart

flutter:
  uses-material-design: true

  assets:
    - assets/env/
    - assets/images/onboarding/
    - assets/images/misc/
    - assets/images/avatar/
    - assets/images/exercise/
