// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IGRLlDB_S_1JyUjbd14LubrEK6424Bw',
    appId: '1:829826821481:android:1653262a7c3422f2a261f8',
    messagingSenderId: '829826821481',
    projectId: 'vocab-booster-91wak0',
    storageBucket: 'vocab-booster-91wak0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUTOVE8iA9NRZkLWJtwt2NpABjz40JA_Y',
    appId: '1:829826821481:ios:a55645516b2eece1a261f8',
    messagingSenderId: '829826821481',
    projectId: 'vocab-booster-91wak0',
    storageBucket: 'vocab-booster-91wak0.appspot.com',
    androidClientId: '829826821481-jise7lihj3lim8horpi060dejb0m5qfe.apps.googleusercontent.com',
    iosClientId: '829826821481-d2nf673a37tmbhptnkmef8vci63pflq2.apps.googleusercontent.com',
    iosBundleId: 'vocab.booster.app',
  );

}